server:
  port: 8080
  servlet:
    context-path: /exam
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.73.146:3306/exam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: zzq123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyg.exam.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
